// Generated by gencpp from file stage/xygoal.msg
// DO NOT EDIT!


#ifndef STAGE_MESSAGE_XYGOAL_H
#define STAGE_MESSAGE_XYGOAL_H

#include <ros/service_traits.h>


#include <stage/xygoalRequest.h>
#include <stage/xygoalResponse.h>


namespace stage
{

struct xygoal
{

typedef xygoalRequest Request;
typedef xygoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct xygoal
} // namespace stage


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stage::xygoal > {
  static const char* value()
  {
    return "8cd126f9c228a58c5310ae0dba804564";
  }

  static const char* value(const ::stage::xygoal&) { return value(); }
};

template<>
struct DataType< ::stage::xygoal > {
  static const char* value()
  {
    return "stage/xygoal";
  }

  static const char* value(const ::stage::xygoal&) { return value(); }
};


// service_traits::MD5Sum< ::stage::xygoalRequest> should match
// service_traits::MD5Sum< ::stage::xygoal >
template<>
struct MD5Sum< ::stage::xygoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stage::xygoal >::value();
  }
  static const char* value(const ::stage::xygoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage::xygoalRequest> should match
// service_traits::DataType< ::stage::xygoal >
template<>
struct DataType< ::stage::xygoalRequest>
{
  static const char* value()
  {
    return DataType< ::stage::xygoal >::value();
  }
  static const char* value(const ::stage::xygoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stage::xygoalResponse> should match
// service_traits::MD5Sum< ::stage::xygoal >
template<>
struct MD5Sum< ::stage::xygoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stage::xygoal >::value();
  }
  static const char* value(const ::stage::xygoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stage::xygoalResponse> should match
// service_traits::DataType< ::stage::xygoal >
template<>
struct DataType< ::stage::xygoalResponse>
{
  static const char* value()
  {
    return DataType< ::stage::xygoal >::value();
  }
  static const char* value(const ::stage::xygoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAGE_MESSAGE_XYGOAL_H
