// Generated by gencpp from file planner/GoTo.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_GOTO_H
#define PLANNER_MESSAGE_GOTO_H

#include <ros/service_traits.h>


#include <planner/GoToRequest.h>
#include <planner/GoToResponse.h>


namespace planner
{

struct GoTo
{

typedef GoToRequest Request;
typedef GoToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoTo
} // namespace planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner::GoTo > {
  static const char* value()
  {
    return "2dfe331712db6ce37561cc7498574abd";
  }

  static const char* value(const ::planner::GoTo&) { return value(); }
};

template<>
struct DataType< ::planner::GoTo > {
  static const char* value()
  {
    return "planner/GoTo";
  }

  static const char* value(const ::planner::GoTo&) { return value(); }
};


// service_traits::MD5Sum< ::planner::GoToRequest> should match
// service_traits::MD5Sum< ::planner::GoTo >
template<>
struct MD5Sum< ::planner::GoToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner::GoTo >::value();
  }
  static const char* value(const ::planner::GoToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::GoToRequest> should match
// service_traits::DataType< ::planner::GoTo >
template<>
struct DataType< ::planner::GoToRequest>
{
  static const char* value()
  {
    return DataType< ::planner::GoTo >::value();
  }
  static const char* value(const ::planner::GoToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner::GoToResponse> should match
// service_traits::MD5Sum< ::planner::GoTo >
template<>
struct MD5Sum< ::planner::GoToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner::GoTo >::value();
  }
  static const char* value(const ::planner::GoToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner::GoToResponse> should match
// service_traits::DataType< ::planner::GoTo >
template<>
struct DataType< ::planner::GoToResponse>
{
  static const char* value()
  {
    return DataType< ::planner::GoTo >::value();
  }
  static const char* value(const ::planner::GoToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MESSAGE_GOTO_H
