// Generated by gencpp from file turtle_pid_control/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TURTLE_PID_CONTROL_MESSAGE_ADDTWOINTS_H
#define TURTLE_PID_CONTROL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <turtle_pid_control/AddTwoIntsRequest.h>
#include <turtle_pid_control/AddTwoIntsResponse.h>


namespace turtle_pid_control
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace turtle_pid_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_pid_control::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::turtle_pid_control::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::turtle_pid_control::AddTwoInts > {
  static const char* value()
  {
    return "turtle_pid_control/AddTwoInts";
  }

  static const char* value(const ::turtle_pid_control::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_pid_control::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::turtle_pid_control::AddTwoInts >
template<>
struct MD5Sum< ::turtle_pid_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_pid_control::AddTwoInts >::value();
  }
  static const char* value(const ::turtle_pid_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_pid_control::AddTwoIntsRequest> should match
// service_traits::DataType< ::turtle_pid_control::AddTwoInts >
template<>
struct DataType< ::turtle_pid_control::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_pid_control::AddTwoInts >::value();
  }
  static const char* value(const ::turtle_pid_control::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_pid_control::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::turtle_pid_control::AddTwoInts >
template<>
struct MD5Sum< ::turtle_pid_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_pid_control::AddTwoInts >::value();
  }
  static const char* value(const ::turtle_pid_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_pid_control::AddTwoIntsResponse> should match
// service_traits::DataType< ::turtle_pid_control::AddTwoInts >
template<>
struct DataType< ::turtle_pid_control::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_pid_control::AddTwoInts >::value();
  }
  static const char* value(const ::turtle_pid_control::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_PID_CONTROL_MESSAGE_ADDTWOINTS_H
